# Generated by Django 5.1.6 on 2025-02-19 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_transaction_id_alter_payment_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
