# Generated by Django 5.1.2 on 2025-01-08 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='uid',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
