# Generated by Django 5.1.2 on 2024-10-23 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowerCareTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('flower_type', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recommended_water_frequency', models.CharField(max_length=100)),
                ('sunlight_needs', models.CharField(max_length=100)),
                ('special_notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
