# Generated by Django 5.1.2 on 2024-10-23 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0003_remove_flowercaretip_flower_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantRevivalTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_name', models.CharField(max_length=255, verbose_name='Plant Name')),
                ('symptoms', models.TextField(verbose_name='Symptoms of Dying')),
                ('revival_steps', models.TextField(verbose_name='Steps to Revive the Plant')),
                ('recommended_fertilizer', models.CharField(max_length=100, verbose_name='Recommended Fertilizer')),
                ('watering_caution', models.CharField(max_length=100, verbose_name='Watering Guidelines')),
                ('sunlight_adjustment', models.CharField(max_length=100, verbose_name='Sunlight Adjustment Advice')),
                ('recommended_water_frequency', models.CharField(max_length=100, verbose_name='Watering Frequency')),
                ('special_notes', models.TextField(blank=True, null=True, verbose_name='Additional Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated On')),
            ],
        ),
        migrations.DeleteModel(
            name='FlowerCareTip',
        ),
    ]
