# Generated by Django 5.1.2 on 2024-12-31 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0007_remove_comment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
