# Generated by Django 5.1.2 on 2025-01-02 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0011_remove_comment_user_comment_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
    ]
