# Generated by Django 5.1.2 on 2025-01-06 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0022_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='quantity',
        ),
    ]
