# Generated by Django 5.1.2 on 2025-01-06 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0024_cartitem_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='quantity',
        ),
    ]
