# Generated by Django 5.1.2 on 2025-01-07 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0026_cartitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
