# Generated by Django 5.1.2 on 2025-01-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0028_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
