# Generated by Django 5.1.2 on 2024-10-27 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0006_plantrevivaltip_sunlight_needs'),
        ('orders', '0002_order_profit_order_revenue'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flowerPrice', to='flowers.flower'),
        ),
    ]
