# Generated by Django 5.1.2 on 2025-01-15 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_transaction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='transaction_id',
        ),
    ]
