# Generated by Django 5.1.6 on 2025-02-19 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_transaction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='transaction_id',
        ),
    ]
