# Generated by Django 5.1.6 on 2025-02-19 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_order_transaction_id_alter_order_flower_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='profit',
        ),
        migrations.RemoveField(
            model_name='order',
            name='revenue',
        ),
    ]
