# Generated by Django 5.2.4 on 2025-10-15 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_order_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
    ]
